### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by edubart** [lunarmodules/luacov#83]
Lua 5.4 is officially released, what is needed to support it in `luacov` and `cluacov` too?

**Comment by Tieske** [comment]
the rockspec has a constraint on Lua 5.1 - 5.3, while there is an older rockspec (0.11 version) that does not set a constraint. This currently results in the old 0.11 version being installed on a Lua 5.4 installation by LuaRocks.

Other than that LuaCov itself seems to work fine, but `cluacov` requires some work. I did a cheap copy-paste experiment, but that didn't work, the tests kept failing.

@hishamhm how to move this forward?

**Comment by Tieske** [comment]
experiment here: https://github.com/luarocks/cluacov/pull/1

**Comment by hishamhm** [comment]
Closed by #84!
