### ISSUE TITLE
exclude goto statements and labels from accounting

### ISSUE THREAD

**Issue by myk002** [lunarmodules/luacov#89]
In Lua 5.1.5 at least, `goto` statements and target labels are never accounted as having coverage, even if the surrounding code coverage makes it obvious that the line has been hit. This artificially lowers the code coverage metric.

The following two lines added to `any_hits_exclusions` or `zero_hits_exclusions` fixes the issue for me:
```
"goto [%w_]+", -- goto statements
"::[%w_]+::", -- labels
```

but I don't know if there are differences on other platforms/Lua implementations.

**Comment by hishamhm** [comment]
Fixed in #95!
