### ISSUE TITLE
Repo website url is outdated

### ISSUE THREAD

**Issue by mrpudn** [lunarmodules/luacov#99]
Related to a1aa1fefb44904c3e0ac2a1fe064064b4ccfef55

From my reading, it looks like this module is being transitioned.

Just a friendly reminder that this repo's website url has not been updated to the new url:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/2818916/184075924-ce7f8a46-5997-4777-90c8-1e72d70d3c1c.png">

Old url: https://keplerproject.github.io/luacov/

New url: https://lunarmodules.github.io/luacov/

---

Likewise, the LuaRocks module homepage is outdated:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/2818916/184076213-58ad796a-2c31-4545-8be9-165ae71db5d9.png">

**Comment by hishamhm** [comment]
Thanks for the heads up! fixed
